// Javascript approach using pkg
var planeList = ['B707', 'B717', 'B727', 'B737', 'B747', 'B757', 'B767', 'B777', 'B787', 'C-17', 'KC-135', 
'F/A-18', 'F-15', 'A300', 'A320', 'A330', 'A340', 'A350', 'A380', 'DC-3', 'DC-8', 'DC-9', 'DC-10', 'MD-11', 'L1011',
 'F-22', 'C-130'
 ]
var planeFacts = ['The Boeing 707 is an American long-range narrow-body airliner,\n the first jetliner developed and produced by Boeing Commercial Airplanes. Developed from the Boeing 367-80 prototype first flown in 1954, the initial 707-120 first flew on December 20, 1957. \nPan Am began regular 707 service on October 26, 1958. With versions produced until 1979, the 707 was a swept wing quadjet with podded engines. \nIts larger fuselage cross-section allowed six-abreast economy seating, retained in the later 720, 727, 737, and 757 models.', 
'The Boeing 717 is an American five-abreast narrow-body airliner produced by Boeing Commercial Airplanes. \nThe twin-engine airliner was developed for the 100-seat market and originally marketed by McDonnell Douglas in the early 1990s as the MD-95 until the company merged with Boeing in August 1997. \nIt was a shortened derivative of McDonnell Douglas’ successful airliner, the MD-80, and part of the company’s broader DC-9 family. \nCapable of seating up to 134 passengers, the 717 has a design range of 2,060 nautical miles [nmi] (3,820 km; 2,370 mi). \nIt is powered by two Rolls-Royce BR715 turbofan engines mounted at the rear of the fuselage.', 
'The Boeing 727 is an American narrow-body airliner that was developed and produced by Boeing Commercial Airplanes. \nAfter the heavier 707 quad-jet was introduced in 1958, Boeing addressed the demand for shorter flight lengths from smaller airports. \nOn December 5, 1960, the 727 was launched with 40 orders each from United Airlines and Eastern Air Lines. \nThe first 727-100 rolled out on November 27, 1962, first flew on February 9, 1963, and entered service with Eastern on February 1, 1964.', 
'The Boeing 737 is a narrow-body aircraft produced by Boeing at its Everett and Renton factories in Washington. \nDeveloped to supplement the Boeing 727 on short and thin routes, the twinjet retained the 707 fuselage width and six abreast seating but with two underwing turbofans instead of four. \nEnvisioned in 1964, the initial 737-100 made its first flight in April 1967 and entered service in February 1968 with Lufthansa. \nThe lengthened 737-200 entered service in April 1968, and evolved through four generations, offering several variants for 85 to 215 passengers.', 
'The Boeing 747 is a large, long-range wide-body airliner designed and manufactured by Boeing Commercial Airplanes in the United States between 1968 and 2023. \nAfter introducing the 707 in October 1958, Pan Am wanted a jet 2+1⁄2 times its size, to reduce its seat cost by 30%. \nIn 1965, Joe Sutter left the 737 development program to design the 747. In April 1966, Pan Am ordered 25 Boeing 747-100 aircraft, \nand in late 1966, Pratt & Whitney agreed to develop the JT9D engine, a high-bypass turbofan. \nOn September 30, 1968, the first 747 was rolled out of the custom-built Everett Plant, the worlds largest building by volume. \nThe first flight took place on February 9, 1969, and the 747 was certified in December of that year. \nIt entered service with Pan Am on January 22, 1970. The 747 was the first airplane called a "Jumbo Jet" as the first wide-body airliner.', 
'The Boeing 757 is an American narrow-body airliner designed and built by Boeing Commercial Airplanes. \nThe then-named 7N7, a twinjet successor for the trijet 727, received its first orders in August 1978. The \nprototype completed its maiden flight on February 19, 1982, and it was FAA certified on December 21, 1982. Eastern Air Lines placed the initial \n757-200 variant in commercial service on January 1, 1983. A package freighter (PF) variant entered service in September 1987 \nand a combi model in September 1988. The stretched 757-300 was launched in September 1996 and began service in March 1999. \nAfter 1,050 had been built for 54 customers, production ended in October 2004, while Boeing offered the largest 737 NG variants as a successor.',
'The Boeing 767 is an American wide-body aircraft developed and manufactured by Boeing Commercial Airplanes. \nThe aircraft was launched as the 7X7 program\n on July 14, 1978, the prototype first flew on September 26, 1981, and it was certified on July 30, 1982. The initial 767-200 variant entered service on September 8, 1982,\n with United Airlines, and the extended-range 767-200ER in 1984. It was stretched into the \n767-300 in October 1986, followed by the 767-300ER in 1988, the most popular variant. The 767-300F, a production freighter version, \ndebuted in October 1995. It was stretched again into the 767-400ER from September 2000.', 
]
function main(){
   console.log(planeFacts[Math.floor(Math.random(0, 6))])
   UserInput = input('Enter to exit, r to restart')
   if (UserInput.toLowerCase === 'r'){
    main()
   }}
main()